export function renewalTemplate(
  request,
  newDueDate
) {
  return `...`;
}

export function returnTemplate(
  request
) {
  return `...`;
}
export function issueBookTemplate(
  request,
  issueDate,
  dueDate
) {
  return `
<div style="
max-width:700px;
margin:auto;
font-family:Arial,Helvetica,sans-serif;
border:1px solid #ddd;
border-radius:12px;
overflow:hidden;
">

<div style="
background:#6f4e37;
color:white;
padding:20px;
text-align:center;
">

<h2 style="margin:0;">
📚 Bhaktivedanta Rajavidyalaya
</h2>

<p style="margin-top:8px;">
ISKCON NVCC, Pune
</p>

</div>

<div style="padding:30px;">

<p>
Dear
<strong>${request.studentName}</strong>,
</p>

<p>
Hare Krishna!
</p>

<p>
Your requested book has been approved successfully.
</p>

<hr>

<h3 style="color:#6f4e37;">
📖 Book Details
</h3>

<table style="width:100%;">

<tr>
<td><strong>Book</strong></td>
<td>${request.bookName}</td>
</tr>

<tr>
<td><strong>Author</strong></td>
<td>${request.author}</td>
</tr>

<tr>
<td><strong>Language</strong></td>
<td>${request.language}</td>
</tr>

<tr>
<td><strong>Location</strong></td>
<td>${request.position}</td>
</tr>

<tr>
<td><strong>Issue Date</strong></td>
<td>${issueDate.toLocaleDateString("en-GB")}</td>
</tr>

<tr>
<td><strong>Due Date</strong></td>
<td>${dueDate.toLocaleDateString("en-GB")}</td>
</tr>

</table>

<br>

<div style="
background:#fff7e6;
border-left:5px solid orange;
padding:15px;
">

<strong>

Please collect your book from the
Bhaktivedanta Rajavidyalaya Office
during working hours [10am to 1pm and 2.30pm to 6.30pm].

</strong>

</div>

<br>

Please return the book on or before the due date.

If you require additional time,
please request a renewal before the due date.

<hr>

<p>

Your Servant,

<br><br>

<strong>
Bhaktivedanta Rajavidyalaya
</strong>

<br>

ISKCON NVCC, Pune

</p>

<p style="
font-size:13px;
color:#777;
">

This is an automated email generated by the
Bhaktivedanta Rajavidyalaya Library Management System.

<br><br>

<strong>
Please do not reply to this email.
</strong>

<br><br>

For assistance regarding your library account
or book transactions,
please contact the BVRV Office.

</p>

</div>

</div>
`;
}
export function renewBookTemplate(
  request,
  newDueDate
) {
  return `
<div style="
max-width:700px;
margin:auto;
font-family:Arial,Helvetica,sans-serif;
border:1px solid #ddd;
border-radius:12px;
overflow:hidden;
">

<div style="
background:#6f4e37;
color:white;
padding:20px;
text-align:center;
">

<h2 style="margin:0;">
📚 Bhaktivedanta Rajavidyalaya
</h2>

<p style="margin-top:8px;">
ISKCON NVCC, Pune
</p>

</div>

<div style="padding:30px;">

<p>
Dear <strong>${request.studentName}</strong>,
</p>

<p>
Hare Krishna!
</p>

<p>
We are pleased to inform you that your library book has been renewed successfully.
</p>

<hr>

<h3 style="color:#6f4e37;">
📖 Book Details
</h3>

<table style="
width:100%;
border-collapse:collapse;
">

<tr>
<td style="padding:8px;"><strong>Book</strong></td>
<td style="padding:8px;">${request.bookName}</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:8px;"><strong>Author</strong></td>
<td style="padding:8px;">${request.author}</td>
</tr>

<tr>
<td style="padding:8px;"><strong>Language</strong></td>
<td style="padding:8px;">${request.language}</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:8px;"><strong>Location</strong></td>
<td style="padding:8px;">${request.position}</td>
</tr>

<tr>
<td style="padding:8px;"><strong>New Due Date</strong></td>
<td style="padding:8px;">
${newDueDate.toLocaleDateString("en-GB")}
</td>
</tr>

</table>

<br>

<div style="
background:#e8f5e9;
border-left:5px solid #28a745;
padding:15px;
">

<strong>
✅ Your renewal request has been approved successfully.
</strong>

</div>

<br>

<div style="
background:#fff7e6;
border-left:5px solid orange;
padding:15px;
">

<strong>

Please return the book on or before
${newDueDate.toLocaleDateString("en-GB")}.

</strong>

</div>

<hr>

<p>

Your Servant,

<br><br>

<strong>
Bhaktivedanta Rajavidyalaya
</strong>

<br>

ISKCON NVCC, Pune

</p>

<p style="
font-size:13px;
color:#777;
">

This is an automated email generated by the
Bhaktivedanta Rajavidyalaya Library Management System.

<br><br>

<strong>
Please do not reply to this email.
</strong>

<br><br>

For assistance regarding your library account or book transactions,
please contact the BVRV Office.

</p>

</div>

</div>
`;
}

export function returnBookTemplate(
  request
) {
  return `
<div style="
max-width:700px;
margin:auto;
font-family:Arial,Helvetica,sans-serif;
border:1px solid #ddd;
border-radius:12px;
overflow:hidden;
">

<div style="
background:#6f4e37;
color:white;
padding:20px;
text-align:center;
">

<h2 style="margin:0;">
📚 Bhaktivedanta Rajavidyalaya
</h2>

<p style="margin-top:8px;">
ISKCON NVCC, Pune
</p>

</div>

<div style="padding:30px;">

<p>
Dear <strong>${request.studentName}</strong>,
</p>

<p>
Hare Krishna!
</p>

<p>
Thank you for returning your library book.
Your return has been recorded successfully.
</p>

<hr>

<h3 style="color:#6f4e37;">
📖 Returned Book Details
</h3>

<table style="
width:100%;
border-collapse:collapse;
">

<tr>
<td style="padding:8px;"><strong>Book</strong></td>
<td style="padding:8px;">${request.bookName}</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:8px;"><strong>Author</strong></td>
<td style="padding:8px;">${request.author}</td>
</tr>

<tr>
<td style="padding:8px;"><strong>Language</strong></td>
<td style="padding:8px;">${request.language}</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:8px;"><strong>Location</strong></td>
<td style="padding:8px;">${request.position}</td>
</tr>

</table>

<br>

<div style="
background:#e8f5e9;
border-left:5px solid #28a745;
padding:15px;
">

<strong>
✅ Thank you for returning the book on time.

We appreciate your support in maintaining the BVRV Library collection for all students.
</strong>

</div>

<hr>

<p>

Your Servant,

<br><br>

<strong>
Bhaktivedanta Rajavidyalaya
</strong>

<br>

ISKCON NVCC, Pune

</p>

<p style="
font-size:13px;
color:#777;
">

This is an automated email generated by the
Bhaktivedanta Rajavidyalaya Library Management System.

<br><br>

<strong>
Please do not reply to this email.
</strong>

<br><br>

For assistance regarding your library account or book transactions,
please contact the BVRV Office.

</p>

</div>

</div>
`;
}


export function registrationApprovedTemplate(studentName) {
  return `
<div style="
max-width:700px;
margin:auto;
font-family:Arial,Helvetica,sans-serif;
border:1px solid #ddd;
border-radius:12px;
overflow:hidden;
background:#ffffff;
">

<div style="
background:linear-gradient(90deg,#6f4e37,#9c6b45);
color:white;
padding:30px;
text-align:center;
">

<h1 style="margin:0;">
🎉 Welcome to BVRV Library
</h1>

<p style="font-size:18px;margin-top:10px;">
Bhaktivedanta Rajavidyalaya
</p>

<p>
ISKCON NVCC, Pune
</p>

</div>

<div style="padding:35px;">

<h2 style="color:#6f4e37;">
Hare Krishna, ${studentName}!
</h2>

<p>

Congratulations!

Your registration for the
<strong>Bhaktivedanta Rajavidyalaya Library</strong>
has been approved successfully.

</p>

<div style="
background:#e8f5e9;
border-left:6px solid #28a745;
padding:18px;
margin:25px 0;
">

<h3 style="margin-top:0;color:#28a745;">
✅ Your Library Account is Now Active
</h3>

You can now log in to the Library Portal and enjoy all library services.

</div>

<h3 style="color:#6f4e37;">
📚 You Can Now
</h3>

<table style="width:100%;border-collapse:collapse;">

<tr>
<td style="padding:10px;">📖 Browse Library Books</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:10px;">📥 Request Available Books</td>
</tr>

<tr>
<td style="padding:10px;">📅 Track Issue & Due Dates</td>
</tr>

<tr style="background:#f8f8f8;">
<td style="padding:10px;">🔄 Renew Issued Books</td>
</tr>

<tr>
<td style="padding:10px;">📜 View Book History</td>
</tr>

</table>

<br>

<div style="
background:#fff7e6;
border-left:6px solid orange;
padding:18px;
">

<strong>
📌 Library Timings
</strong>

<br><br>

Monday – Sunday

<br>

🕙 10:00 AM – 1:00 PM

<br>

🕝 2:30 PM – 6:30 PM

</div>

<br>

<div style="
background:#eef6ff;
border-left:6px solid #0d6efd;
padding:18px;
">

<strong>💡 Library Guidelines</strong>

<ul style="margin-top:10px;">

<li>Return books on or before the due date.</li>

<li>Renew books before the due date whenever required.</li>

<li>Handle all books carefully.</li>

<li>Maintain silence and discipline inside the library.</li>

</ul>

</div>

<br>

<div style="
text-align:center;
background:#f7f7f7;
padding:20px;
border-radius:10px;
">

<h2 style="color:#6f4e37;">
Hare Krishna!
📚✨
</h2>

<p>

May your study of
Śrīla Prabhupāda's books
bring knowledge,
devotion,
and spiritual inspiration.

</p>

</div>

<hr>

<p>

Your Servant,

<br><br>

<strong>
Bhaktivedanta Rajavidyalaya Library
</strong>

<br>

ISKCON NVCC, Pune

</p>

<p style="
font-size:13px;
color:#777;
">

This is an automated email generated by the
Bhaktivedanta Rajavidyalaya Library Management System.

<br><br>

<strong>
Please do not reply to this email.
</strong>

<br><br>

For assistance regarding your library account,
please contact the BVRV Office.

</p>

</div>

</div>
`;
}
