export function renewalTemplate(
  request,
  newDueDate
) {
  return `...`;
}

export function returnTemplate(
  request
) {
  return `...`;
}
export function issueBookTemplate(
  request,
  issueDate,
  dueDate
) {
  return `
<div style="
max-width:700px;
margin:auto;
font-family:Arial,Helvetica,sans-serif;
border:1px solid #ddd;
border-radius:12px;
overflow:hidden;
">

<div style="
background:#6f4e37;
color:white;
padding:20px;
text-align:center;
">

<h2 style="margin:0;">
📚 Bhaktivedanta Rajavidyalaya
</h2>

<p style="margin-top:8px;">
ISKCON NVCC, Pune
</p>

</div>

<div style="padding:30px;">

<p>
Dear
<strong>${request.studentName}</strong>,
</p>

<p>
Hare Krishna!
</p>

<p>
Your requested book has been approved successfully.
</p>

<hr>

<h3 style="color:#6f4e37;">
📖 Book Details
</h3>

<table style="width:100%;">

<tr>
<td><strong>Book</strong></td>
<td>${request.bookName}</td>
</tr>

<tr>
<td><strong>Author</strong></td>
<td>${request.author}</td>
</tr>

<tr>
<td><strong>Language</strong></td>
<td>${request.language}</td>
</tr>

<tr>
<td><strong>Location</strong></td>
<td>${request.position}</td>
</tr>

<tr>
<td><strong>Issue Date</strong></td>
<td>${issueDate.toLocaleDateString("en-GB")}</td>
</tr>

<tr>
<td><strong>Due Date</strong></td>
<td>${dueDate.toLocaleDateString("en-GB")}</td>
</tr>

</table>

<br>

<div style="
background:#fff7e6;
border-left:5px solid orange;
padding:15px;
">

<strong>

Please collect your book from the
Bhaktivedanta Rajavidyalaya Office
during working hours [10am to 1pm and 2.30pm to 6.30pm].

</strong>

</div>

<br>

Please return the book on or before the due date.

If you require additional time,
please request a renewal before the due date.

<hr>

<p>

Your Servant,

<br><br>

<strong>
Bhaktivedanta Rajavidyalaya
</strong>

<br>

ISKCON NVCC, Pune

</p>

<p style="
font-size:13px;
color:#777;
">

This is an automated email generated by the
Bhaktivedanta Rajavidyalaya Library Management System.

<br><br>

<strong>
Please do not reply to this email.
</strong>

<br><br>

For assistance regarding your library account
or book transactions,
please contact the BVRV Office.

</p>

</div>

</div>
`;
}
