function getAdminSummaryTemplate(summary) {

  const rows = summary.map((book) => `
    <tr>
      <td style="padding:10px;border:1px solid #ddd;">${book.studentName}</td>
      <td style="padding:10px;border:1px solid #ddd;">${book.bookName}</td>
      <td style="padding:10px;border:1px solid #ddd;">${book.author}</td>
      <td style="padding:10px;border:1px solid #ddd;text-align:center;">${book.daysOverdue}</td>
    </tr>
  `).join("");

  return `
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
</head>

<body style="margin:0;padding:30px;background:#f4f4f4;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="center">

<table width="800" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">

<tr>
<td style="background:#6f4e37;color:#ffffff;padding:20px;text-align:center;">
<h2 style="margin:0;">Bhaktivedanta Rajavidyalaya</h2>
<div>Library Management System</div>
</td>
</tr>

<tr>
<td style="padding:30px;">

<h2 style="margin-top:0;color:#C62828;">
Library Overdue Summary
</h2>

<p>
The following books have reached an overdue milestone today.
</p>

<table
width="100%"
cellpadding="0"
cellspacing="0"
style="border-collapse:collapse;">

<tr style="background:#6f4e37;color:white;">
<th style="padding:10px;">Student</th>
<th style="padding:10px;">Book</th>
<th style="padding:10px;">Author</th>
<th style="padding:10px;">Days Overdue</th>
</tr>

${rows}

</table>

<br>

<p>
<strong>Total Students :</strong> ${summary.length}
</p>

</td>
</tr>

<tr>
<td style="background:#eeeeee;padding:15px;text-align:center;font-size:12px;color:#666;">
Automated email generated by the BVRV Library Management System.
</td>
</tr>

</table>

</td>
</tr>
</table>

</body>
</html>
`;
}

module.exports = {
  getAdminSummaryTemplate,
};
